import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Carrousel from 'nuka-carousel';

import {
  Main,
  ImageContainer,
  ContainerDescription,
  DescriptionContainer,
  CommentContainer,
} from './styles';

import { ContainerMain } from '../../theme/globalstyles';

const Home: NextPage = () => (
  <Main>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    Error
  </Main>
);

export default Home;
