import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Carrousel from 'nuka-carousel';

import {
  Main,
  ImageContainer,
  ContainerDescription,
  DescriptionContainer,
  CommentContainer,
} from './styles';

import Input from '../../components/Form/Input';
import Textarea from '../../components/Form/TextArea';
import { ContainerMain } from '../../theme/globalstyles';

const CreateGame: NextPage = () => (
  <Main>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ContainerMain>
      <ImageContainer>
        <img
          alt="32"
          src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
        />
      </ImageContainer>
      <ContainerDescription>
        <div>
          <Input labelValue="Nome" />
        </div>
        <Textarea
          container={{ className: 'height' }}
          labelValue="Descrição"
          maxValue="100"
        />
      </ContainerDescription>
    </ContainerMain>
  </Main>
);

export default CreateGame;
