import Head from 'next/head';
import { useRouter } from 'next/router';
import { useRef } from 'react';

import { Main, ImageContainer, ContainerDescription } from './styles';

import Button from '../../components/Form/Button';
import Input from '../../components/Form/Input';
import useDimension from '../../hooks/useDimension';
import { ContainerMain } from '../../theme/globalstyles';

const Perfil = () => {
  const ref = useRef(null);
  const { width } = useDimension(ref);
  const router = useRouter();
  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerMain>
        <ImageContainer ref={ref} height={width}>
          <img alt="32" src="" />
        </ImageContainer>
        <ContainerDescription>
          <div>
            <h2>Nome</h2>
            <p>name</p>
          </div>
          <div>
            <h2>Email</h2>
            <p>emal</p>
          </div>
          <div>
            <h2>Senha</h2>
            <div>
              <Input
                labelValue="Nova Senha"
                container={{
                  className: 'input',
                }}
              />
              <Button className="button">Confirmar</Button>
            </div>
            <Button
              className="button_company"
              onClick={() => router.push('/createCompany')}
            >
              Criar uma empresa
            </Button>
          </div>
        </ContainerDescription>
      </ContainerMain>
    </Main>
  );
};

export default Perfil;
