import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Carrousel from 'nuka-carousel';

import {
  Main,
  ImageContainer,
  ContainerDescription,
  DescriptionContainer,
  CommentContainer,
} from './styles';

import { ContainerMain } from '../../theme/globalstyles';

const Home: NextPage = () => (
  <Main>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <ContainerMain>
      <ImageContainer>
        <img
          alt="32"
          src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
        />
      </ImageContainer>
      <ContainerDescription>
        <div>
          <h2>Nome</h2>
          <p>Nome</p>
        </div>
        <div>
          <h2>Descrição</h2>
          <p>Descrição</p>
        </div>
        <div>
          <h2>Avaliação</h2>
          <p>Avaliação</p>
        </div>
      </ContainerDescription>
      <DescriptionContainer>
        <h2>Descrição</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean semper
          placerat enim in pretium. Nullam malesuada finibus lacus nec commodo.
          Phasellus a felis suscipit, pellentesque nisl at, vestibulum purus.
          Donec et ultrices urna. Lorem ipsum dolor sit amet, consectetur
          adipiscing elit. Sed in accumsan turpis. Sed eget pharetra metus,
          accumsan posuere odio. Vivamus eleifend felis eu leo semper vulputate.
          Donec faucibus laoreet vulputate. Duis interdum efficitur efficitur.
          Nulla eget tortor felis. Sed quis nibh at mi consequat sodales at ut
          eros. Vestibulum laoreet fringilla mauris, nec interdum nibh convallis
          ac.
        </p>
      </DescriptionContainer>
      <DescriptionContainer>
        <h2>Comentários</h2>
        <CommentContainer>
          <div>
            <img
              alt="32"
              src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
            />
            <h3>Lucas</h3>
          </div>
          <p>fasfdsafdasfsdafsd</p>
        </CommentContainer>
        <CommentContainer>
          <div>
            <img
              alt="32"
              src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
            />
            <h3>Lucas</h3>
          </div>
          <p>fasfdsafdasfsdafsd</p>
        </CommentContainer>
        <CommentContainer>
          <div>
            <img
              alt="32"
              src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
            />
            <h3>Lucas</h3>
          </div>
          <p>fasfdsafdasfsdafsd</p>
        </CommentContainer>
        <CommentContainer>
          <div>
            <img
              alt="32"
              src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
            />
            <h3>Lucas</h3>
          </div>
          <p>fasfdsafdasfsdafsd</p>
        </CommentContainer>
        <CommentContainer>
          <div>
            <img
              alt="32"
              src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
            />
            <h3>Lucas</h3>
          </div>
          <p>fasfdsafdasfsdafsd</p>
        </CommentContainer>
      </DescriptionContainer>
    </ContainerMain>
  </Main>
);

export default Home;
