import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { useContext } from 'react';
import Rating from 'react-star-ratings';
import { ThemeContext } from 'styled-components';

import {
  Main,
  ImageContainer,
  ContainerDescription,
  DescriptionContainer,
  CommentContainer,
} from './styles';

import { findGame } from '../../services/api/game';
import { ContainerMain } from '../../theme/globalstyles';

interface gamesProps {
  id: number;
  name: string;
  description: string;
  file_url: string;
  company: {
    id: number;
    name: string;
    description: string;
    file_url: string;
  };
  reviewMed: number;
}

const Game: NextPage<{
  gameProps: gamesProps;
}> = ({ gameProps }) => {
  const theme = useContext(ThemeContext);

  return (
    <Main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerMain>
        <ImageContainer>
          <img alt="32" src={gameProps.file_url} />
        </ImageContainer>
        <ContainerDescription>
          <div>
            <h2>Nome</h2>
            <p>{gameProps.name}</p>
          </div>
          <div>
            <h2>Empresa</h2>
            <p>{gameProps.company.name}</p>
          </div>
          <div>
            <h2>Avaliação</h2>
            <Rating
              rating={gameProps.reviewMed || 0}
              starRatedColor={theme.background.secondary}
              changeRating={() => {}}
              numberOfStars={5}
              name="rating"
            />
          </div>
        </ContainerDescription>
        <DescriptionContainer>
          <h2>Descrição</h2>
          <p>{gameProps.description}</p>
        </DescriptionContainer>
        <DescriptionContainer>
          <h2>Comentários</h2>
          <CommentContainer>
            <div>
              <img
                alt="32"
                src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
              />
              <h3>Lucas</h3>
            </div>
            <p>fasfdsafdasfsdafsd</p>
          </CommentContainer>
          <CommentContainer>
            <div>
              <img
                alt="32"
                src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
              />
              <h3>Lucas</h3>
            </div>
            <p>fasfdsafdasfsdafsd</p>
          </CommentContainer>
          <CommentContainer>
            <div>
              <img
                alt="32"
                src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
              />
              <h3>Lucas</h3>
            </div>
            <p>fasfdsafdasfsdafsd</p>
          </CommentContainer>
          <CommentContainer>
            <div>
              <img
                alt="32"
                src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
              />
              <h3>Lucas</h3>
            </div>
            <p>fasfdsafdasfsdafsd</p>
          </CommentContainer>
          <CommentContainer>
            <div>
              <img
                alt="32"
                src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1Dyth-2BFxRq7IAuG0jK0wHaEK%26pid%3DApi&f=1"
              />
              <h3>Lucas</h3>
            </div>
            <p>fasfdsafdasfsdafsd</p>
          </CommentContainer>
        </DescriptionContainer>
      </ContainerMain>
    </Main>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  try {
    const game = await findGame(params.id);
    game.data.file_url = `${process.env.REACT_APP_URL}/${game.data.file_url}`;
    game.data.company.file_url = `${process.env.REACT_APP_URL}/${game.data.company.file_url}`;
    console.log(game);

    return {
      props: {
        gameProps: game.data,
      },
    };
  } catch (e) {
    console.log(e);
    return {
      props: {},
    };
  }
};

export default Game;
